clear;

%% parameter settings
sampling_us = 0.001; % sampling rate in 1E-6s time unit
DAC_elapse_period_us = 1; % DAC pulse elapse in 1E-6 time unit
extra_cp_number = 0; % extra cp appended
%% CP detection
% generate pilot pulse
pilot_pulse = [1, zeros(1, 31)];
% obtain pilot pulse for cp detection use
delay_number = OFDMEstimate_Delay( ...
    pilot_pulse, ...
    DAC_elapse_period_us, ...
    sampling_us ...
);
%% H(jw) detection
% randomly generate pilot pulses for coefficients detection
% 0.2 to 0.8 random numbers are generated
random_pulse = rand(1, 32) * 0.8 + 0.2;
% obtian pilot pulse for coefficients detection use
estimate_ht_coefficients = OFDMEstimate_Coeff( ...
    random_pulse, ...
    delay_number, ...
    extra_cp_number, ...
    DAC_elapse_period_us, ...
    sampling_us ...
);
%% X(jw) reconstruct
% randomly generate data symbols 
data_symbols = rand(1, 32) * 0.8 + 0.2;
% transmit and reconstruct data symbols based on known cp and coeffs
recv_data_symbols = OFDMTrans( ...
    data_symbols, ...
    delay_number, ...
    extra_cp_number, ...
    estimate_ht_coefficients, ...
    DAC_elapse_period_us, ...
    sampling_us ...
);

figure(1);
subplot(311), stem(data_symbols);
subplot(312), stem(real(recv_data_symbols));
percentage_output = abs(data_symbols - real(recv_data_symbols)) ...
    ./ (abs(data_symbols) / 100);
for iter = 1 : 32
    if (abs(data_symbols(1, iter)) < 0.05)
        percentage_output(1, iter) = 0;
    end
end
subplot(313), stem(percentage_output);
